// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package apis

import (
<<<<<<< HEAD
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
=======
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
>>>>>>> 0efc8eb... 0327
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PersonalInformationList struct {
	Items                []*PersonInformation `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PersonalInformationList) Reset()         { *m = PersonalInformationList{} }
func (m *PersonalInformationList) String() string { return proto.CompactTextString(m) }
func (*PersonalInformationList) ProtoMessage()    {}
func (*PersonalInformationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *PersonalInformationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalInformationList.Unmarshal(m, b)
}
func (m *PersonalInformationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalInformationList.Marshal(b, m, deterministic)
}
func (m *PersonalInformationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalInformationList.Merge(m, src)
}
func (m *PersonalInformationList) XXX_Size() int {
	return xxx_messageInfo_PersonalInformationList.Size(m)
}
func (m *PersonalInformationList) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalInformationList.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalInformationList proto.InternalMessageInfo

func (m *PersonalInformationList) GetItems() []*PersonInformation {
	if m != nil {
		return m.Items
	}
	return nil
}

<<<<<<< HEAD
type PersonInformation struct {
	// @gotags: gorm:"column:name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" gorm:"column:name"`
	// @gotags: gorm:"column:sex"
	Sex string `protobuf:"bytes,2,opt,name=sex,proto3" json:"sex,omitempty" gorm:"column:sex"`
	// @gotags: gorm:"column:tall"
	Tall float32 `protobuf:"fixed32,3,opt,name=tall,proto3" json:"tall,omitempty" gorm:"column:tall"`
	// @gotags: gorm:"column:weight"
	Weight float32 `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty" gorm:"column:weight"`
	// @gotags: gorm:"column:age"
	Age                  int64    `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty" gorm:"column:age"`
=======
type PersonRanks struct {
	PersonRanks          []*PersonRank `protobuf:"bytes,1,rep,name=personRanks,proto3" json:"personRanks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PersonRanks) Reset()         { *m = PersonRanks{} }
func (m *PersonRanks) String() string { return proto.CompactTextString(m) }
func (*PersonRanks) ProtoMessage()    {}
func (*PersonRanks) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *PersonRanks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonRanks.Unmarshal(m, b)
}
func (m *PersonRanks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonRanks.Marshal(b, m, deterministic)
}
func (m *PersonRanks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonRanks.Merge(m, src)
}
func (m *PersonRanks) XXX_Size() int {
	return xxx_messageInfo_PersonRanks.Size(m)
}
func (m *PersonRanks) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonRanks.DiscardUnknown(m)
}

var xxx_messageInfo_PersonRanks proto.InternalMessageInfo

func (m *PersonRanks) GetPersonRanks() []*PersonRank {
	if m != nil {
		return m.PersonRanks
	}
	return nil
}

type PersonInformationFatRate struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FatRate              float32  `protobuf:"fixed32,2,opt,name=fatRate,proto3" json:"fatRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonInformationFatRate) Reset()         { *m = PersonInformationFatRate{} }
func (m *PersonInformationFatRate) String() string { return proto.CompactTextString(m) }
func (*PersonInformationFatRate) ProtoMessage()    {}
func (*PersonInformationFatRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *PersonInformationFatRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonInformationFatRate.Unmarshal(m, b)
}
func (m *PersonInformationFatRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonInformationFatRate.Marshal(b, m, deterministic)
}
func (m *PersonInformationFatRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonInformationFatRate.Merge(m, src)
}
func (m *PersonInformationFatRate) XXX_Size() int {
	return xxx_messageInfo_PersonInformationFatRate.Size(m)
}
func (m *PersonInformationFatRate) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonInformationFatRate.DiscardUnknown(m)
}

var xxx_messageInfo_PersonInformationFatRate proto.InternalMessageInfo

func (m *PersonInformationFatRate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonInformationFatRate) GetFatRate() float32 {
	if m != nil {
		return m.FatRate
	}
	return 0
}

type PersonRank struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex                  string   `protobuf:"bytes,2,opt,name=sex,proto3" json:"sex,omitempty"`
	RankNumber           int64    `protobuf:"varint,3,opt,name=rankNumber,proto3" json:"rankNumber,omitempty"`
	FatRate              float32  `protobuf:"fixed32,4,opt,name=fatRate,proto3" json:"fatRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonRank) Reset()         { *m = PersonRank{} }
func (m *PersonRank) String() string { return proto.CompactTextString(m) }
func (*PersonRank) ProtoMessage()    {}
func (*PersonRank) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *PersonRank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonRank.Unmarshal(m, b)
}
func (m *PersonRank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonRank.Marshal(b, m, deterministic)
}
func (m *PersonRank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonRank.Merge(m, src)
}
func (m *PersonRank) XXX_Size() int {
	return xxx_messageInfo_PersonRank.Size(m)
}
func (m *PersonRank) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonRank.DiscardUnknown(m)
}

var xxx_messageInfo_PersonRank proto.InternalMessageInfo

func (m *PersonRank) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonRank) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *PersonRank) GetRankNumber() int64 {
	if m != nil {
		return m.RankNumber
	}
	return 0
}

func (m *PersonRank) GetFatRate() float32 {
	if m != nil {
		return m.FatRate
	}
	return 0
}

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type PersonInformation struct {
	// @gotags: gorm:"primaryKey;column:id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// @gotags: gorm:"column:name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// @gotags: gorm:"column:sex"
	Sex string `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	// @gotags: gorm:"column:tall"
	Tall float32 `protobuf:"fixed32,4,opt,name=tall,proto3" json:"tall,omitempty"`
	// @gotags: gorm:"column:weight"
	Weight float32 `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	// @gotags: gorm:"column:age"
	Age                  int64    `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
>>>>>>> 0efc8eb... 0327
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonInformation) Reset()         { *m = PersonInformation{} }
func (m *PersonInformation) String() string { return proto.CompactTextString(m) }
func (*PersonInformation) ProtoMessage()    {}
func (*PersonInformation) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_d938547f84707355, []int{1}
=======
	return fileDescriptor_d938547f84707355, []int{5}
>>>>>>> 0efc8eb... 0327
}

func (m *PersonInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonInformation.Unmarshal(m, b)
}
func (m *PersonInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonInformation.Marshal(b, m, deterministic)
}
func (m *PersonInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonInformation.Merge(m, src)
}
func (m *PersonInformation) XXX_Size() int {
	return xxx_messageInfo_PersonInformation.Size(m)
}
func (m *PersonInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonInformation.DiscardUnknown(m)
}

var xxx_messageInfo_PersonInformation proto.InternalMessageInfo

<<<<<<< HEAD
=======
func (m *PersonInformation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

>>>>>>> 0efc8eb... 0327
func (m *PersonInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonInformation) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *PersonInformation) GetTall() float32 {
	if m != nil {
		return m.Tall
	}
	return 0
}

func (m *PersonInformation) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *PersonInformation) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*PersonalInformationList)(nil), "apis.PersonalInformationList")
<<<<<<< HEAD
=======
	proto.RegisterType((*PersonRanks)(nil), "apis.PersonRanks")
	proto.RegisterType((*PersonInformationFatRate)(nil), "apis.PersonInformationFatRate")
	proto.RegisterType((*PersonRank)(nil), "apis.PersonRank")
	proto.RegisterType((*Null)(nil), "apis.null")
>>>>>>> 0efc8eb... 0327
	proto.RegisterType((*PersonInformation)(nil), "apis.PersonInformation")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
<<<<<<< HEAD
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x31, 0x8a, 0xc3, 0x30,
	0x10, 0x45, 0x91, 0x65, 0x1b, 0x76, 0xdc, 0xec, 0xaa, 0x58, 0xab, 0x14, 0xae, 0xd4, 0xc4, 0x45,
	0x72, 0x89, 0x04, 0x52, 0x04, 0xdd, 0x40, 0x81, 0x89, 0x23, 0xb0, 0x25, 0x63, 0x0d, 0x38, 0xb9,
	0x7d, 0x90, 0x9c, 0x22, 0x90, 0xee, 0xcd, 0x9f, 0xf7, 0x8b, 0x0f, 0x0d, 0x3d, 0x67, 0x8c, 0xfd,
	0xbc, 0x04, 0x0a, 0xa2, 0xb4, 0xb3, 0x8b, 0xdd, 0x11, 0xda, 0x0b, 0x2e, 0x31, 0x78, 0x3b, 0x9e,
	0xfc, 0x2d, 0x2c, 0x93, 0x25, 0x17, 0xfc, 0xd9, 0x45, 0x12, 0x3b, 0xa8, 0x1c, 0xe1, 0x14, 0x25,
	0x53, 0x5c, 0x37, 0xfb, 0xb6, 0x4f, 0x85, 0x7e, 0xb3, 0x3f, 0x5c, 0xb3, 0x59, 0xdd, 0x0a, 0x7f,
	0x5f, 0x3f, 0x21, 0xa0, 0xf4, 0x76, 0x42, 0xc9, 0x14, 0xd3, 0x3f, 0x26, 0xb3, 0xf8, 0x05, 0x1e,
	0xf1, 0x21, 0x8b, 0x1c, 0x25, 0x4c, 0x16, 0xd9, 0x71, 0x94, 0x5c, 0x31, 0x5d, 0x98, 0xcc, 0xe2,
	0x1f, 0xea, 0x15, 0xdd, 0x70, 0x27, 0x59, 0xe6, 0xf4, 0x7d, 0xa5, 0xb6, 0x1d, 0x50, 0x56, 0x8a,
	0x69, 0x6e, 0x12, 0x5e, 0xeb, 0xbc, 0xe7, 0xf0, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x61, 0x15,
	0x60, 0xde, 0x00, 0x00, 0x00,
=======
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x8d, 0x93, 0x6c, 0x60, 0x27, 0x08, 0x76, 0xe7, 0x40, 0xad, 0x95, 0x58, 0x45, 0x3e, 0x85,
	0x03, 0x15, 0x2a, 0x07, 0x24, 0x0e, 0x48, 0x5c, 0xb6, 0x45, 0x02, 0x84, 0x4c, 0x11, 0x67, 0xb7,
	0x9d, 0xb6, 0x56, 0xf3, 0xa5, 0xd8, 0xe5, 0xe3, 0x17, 0x70, 0xe7, 0x17, 0xa3, 0x38, 0x29, 0x0d,
	0x84, 0xdc, 0x66, 0xfc, 0xde, 0xbc, 0x37, 0x93, 0xc9, 0x40, 0x6c, 0x7f, 0x54, 0x64, 0xa6, 0x55,
	0x5d, 0xda, 0x12, 0x43, 0x55, 0x69, 0x23, 0x16, 0x30, 0xf9, 0x48, 0xb5, 0x29, 0x0b, 0x95, 0xbd,
	0x2d, 0xb6, 0x65, 0x9d, 0x2b, 0xab, 0xcb, 0xe2, 0x9d, 0x36, 0x16, 0x9f, 0xc1, 0x85, 0xb6, 0x94,
	0x1b, 0xce, 0x92, 0x20, 0x8d, 0x67, 0x93, 0x69, 0x53, 0x30, 0x6d, 0xd9, 0x3d, 0xae, 0x6c, 0x59,
	0xe2, 0x0d, 0xc4, 0x2d, 0x26, 0x55, 0x71, 0x30, 0x38, 0x83, 0xb8, 0x3a, 0xa7, 0x9d, 0xc6, 0x55,
	0x5f, 0xa3, 0x01, 0x64, 0x9f, 0x24, 0x16, 0xc0, 0x07, 0xf2, 0x77, 0xca, 0x4a, 0x65, 0x09, 0x11,
	0xc2, 0x42, 0xe5, 0xc4, 0x59, 0xc2, 0xd2, 0x4b, 0xe9, 0x62, 0xe4, 0x70, 0x6f, 0xdb, 0xc2, 0xdc,
	0x4f, 0x58, 0xea, 0xcb, 0x53, 0x2a, 0x32, 0x80, 0xb3, 0xc9, 0x7f, 0x6b, 0xaf, 0x20, 0x30, 0xf4,
	0xdd, 0xd5, 0x5d, 0xca, 0x26, 0xc4, 0x5b, 0x80, 0x5a, 0x15, 0x87, 0x0f, 0xc7, 0x7c, 0x45, 0x35,
	0x0f, 0x12, 0x96, 0x06, 0xb2, 0xf7, 0xd2, 0x77, 0x0b, 0xff, 0x76, 0x8b, 0x20, 0x2c, 0x8e, 0x59,
	0x26, 0x7e, 0x32, 0xb8, 0x1e, 0x0c, 0x80, 0x0f, 0xc1, 0xd7, 0x1b, 0xe7, 0x1d, 0x48, 0x5f, 0x6f,
	0xfe, 0x74, 0xe3, 0x0f, 0xbb, 0x09, 0xce, 0xdd, 0x20, 0x84, 0x56, 0x65, 0x59, 0x67, 0xe5, 0x62,
	0x7c, 0x0c, 0xd1, 0x37, 0xd2, 0xbb, 0xbd, 0xe5, 0x17, 0xee, 0xb5, 0xcb, 0x9a, 0x6a, 0xb5, 0x23,
	0x1e, 0x39, 0x8b, 0x26, 0x9c, 0xfd, 0x0a, 0x20, 0x6e, 0x46, 0xff, 0x44, 0xf5, 0x57, 0xbd, 0x26,
	0x7c, 0x0d, 0xf7, 0x25, 0xed, 0xb4, 0xb1, 0x54, 0xe3, 0xd8, 0x22, 0x6f, 0xc6, 0x00, 0xe1, 0xe1,
	0x12, 0x26, 0x9f, 0xab, 0x8d, 0xb2, 0x34, 0x1c, 0x6f, 0x54, 0xee, 0x76, 0x04, 0xe8, 0x36, 0x2a,
	0x3c, 0x7c, 0x05, 0xf1, 0x9c, 0xec, 0x9d, 0xb2, 0xe4, 0x56, 0x3c, 0xaa, 0x34, 0xf8, 0x6d, 0x84,
	0x87, 0x4f, 0x21, 0x9a, 0x93, 0x5d, 0x96, 0x15, 0x42, 0x8b, 0x36, 0x1b, 0xb8, 0xb9, 0xfe, 0x97,
	0x69, 0x84, 0x87, 0xef, 0xe1, 0xd1, 0x69, 0xf8, 0x16, 0x30, 0xe3, 0x56, 0x4f, 0xfa, 0xc0, 0xe0,
	0x26, 0x84, 0x97, 0x32, 0x7c, 0x09, 0x0f, 0xbe, 0x28, 0xbb, 0xde, 0x9f, 0xb4, 0xfa, 0xfe, 0xe3,
	0x9f, 0xf0, 0x39, 0x5b, 0x45, 0xee, 0xf0, 0x5e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x11, 0xe2,
	0xc2, 0xd0, 0x87, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RankServiceClient is the client API for RankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RankServiceClient interface {
	Register(ctx context.Context, in *PersonInformation, opts ...grpc.CallOption) (*PersonInformation, error)
	UpdatePersonInformation(ctx context.Context, in *PersonInformation, opts ...grpc.CallOption) (*PersonInformationFatRate, error)
	GetFateRate(ctx context.Context, in *PersonInformation, opts ...grpc.CallOption) (*PersonRank, error)
	GetTop(ctx context.Context, in *Null, opts ...grpc.CallOption) (*PersonRanks, error)
	RegisterPersons(ctx context.Context, opts ...grpc.CallOption) (RankService_RegisterPersonsClient, error)
	WatchPersons(ctx context.Context, in *Null, opts ...grpc.CallOption) (RankService_WatchPersonsClient, error)
}

type rankServiceClient struct {
	cc *grpc.ClientConn
}

func NewRankServiceClient(cc *grpc.ClientConn) RankServiceClient {
	return &rankServiceClient{cc}
}

func (c *rankServiceClient) Register(ctx context.Context, in *PersonInformation, opts ...grpc.CallOption) (*PersonInformation, error) {
	out := new(PersonInformation)
	err := c.cc.Invoke(ctx, "/apis.RankService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) UpdatePersonInformation(ctx context.Context, in *PersonInformation, opts ...grpc.CallOption) (*PersonInformationFatRate, error) {
	out := new(PersonInformationFatRate)
	err := c.cc.Invoke(ctx, "/apis.RankService/UpdatePersonInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) GetFateRate(ctx context.Context, in *PersonInformation, opts ...grpc.CallOption) (*PersonRank, error) {
	out := new(PersonRank)
	err := c.cc.Invoke(ctx, "/apis.RankService/GetFateRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) GetTop(ctx context.Context, in *Null, opts ...grpc.CallOption) (*PersonRanks, error) {
	out := new(PersonRanks)
	err := c.cc.Invoke(ctx, "/apis.RankService/GetTop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankServiceClient) RegisterPersons(ctx context.Context, opts ...grpc.CallOption) (RankService_RegisterPersonsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RankService_serviceDesc.Streams[0], "/apis.RankService/RegisterPersons", opts...)
	if err != nil {
		return nil, err
	}
	x := &rankServiceRegisterPersonsClient{stream}
	return x, nil
}

type RankService_RegisterPersonsClient interface {
	Send(*PersonInformation) error
	CloseAndRecv() (*PersonalInformationList, error)
	grpc.ClientStream
}

type rankServiceRegisterPersonsClient struct {
	grpc.ClientStream
}

func (x *rankServiceRegisterPersonsClient) Send(m *PersonInformation) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rankServiceRegisterPersonsClient) CloseAndRecv() (*PersonalInformationList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PersonalInformationList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rankServiceClient) WatchPersons(ctx context.Context, in *Null, opts ...grpc.CallOption) (RankService_WatchPersonsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RankService_serviceDesc.Streams[1], "/apis.RankService/WatchPersons", opts...)
	if err != nil {
		return nil, err
	}
	x := &rankServiceWatchPersonsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RankService_WatchPersonsClient interface {
	Recv() (*PersonInformation, error)
	grpc.ClientStream
}

type rankServiceWatchPersonsClient struct {
	grpc.ClientStream
}

func (x *rankServiceWatchPersonsClient) Recv() (*PersonInformation, error) {
	m := new(PersonInformation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RankServiceServer is the server API for RankService service.
type RankServiceServer interface {
	Register(context.Context, *PersonInformation) (*PersonInformation, error)
	UpdatePersonInformation(context.Context, *PersonInformation) (*PersonInformationFatRate, error)
	GetFateRate(context.Context, *PersonInformation) (*PersonRank, error)
	GetTop(context.Context, *Null) (*PersonRanks, error)
	RegisterPersons(RankService_RegisterPersonsServer) error
	WatchPersons(*Null, RankService_WatchPersonsServer) error
}

// UnimplementedRankServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRankServiceServer struct {
}

func (*UnimplementedRankServiceServer) Register(ctx context.Context, req *PersonInformation) (*PersonInformation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedRankServiceServer) UpdatePersonInformation(ctx context.Context, req *PersonInformation) (*PersonInformationFatRate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePersonInformation not implemented")
}
func (*UnimplementedRankServiceServer) GetFateRate(ctx context.Context, req *PersonInformation) (*PersonRank, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFateRate not implemented")
}
func (*UnimplementedRankServiceServer) GetTop(ctx context.Context, req *Null) (*PersonRanks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTop not implemented")
}
func (*UnimplementedRankServiceServer) RegisterPersons(srv RankService_RegisterPersonsServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterPersons not implemented")
}
func (*UnimplementedRankServiceServer) WatchPersons(req *Null, srv RankService_WatchPersonsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchPersons not implemented")
}

func RegisterRankServiceServer(s *grpc.Server, srv RankServiceServer) {
	s.RegisterService(&_RankService_serviceDesc, srv)
}

func _RankService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.RankService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).Register(ctx, req.(*PersonInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_UpdatePersonInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).UpdatePersonInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.RankService/UpdatePersonInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).UpdatePersonInformation(ctx, req.(*PersonInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_GetFateRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).GetFateRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.RankService/GetFateRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).GetFateRate(ctx, req.(*PersonInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_GetTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Null)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).GetTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.RankService/GetTop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).GetTop(ctx, req.(*Null))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankService_RegisterPersons_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RankServiceServer).RegisterPersons(&rankServiceRegisterPersonsServer{stream})
}

type RankService_RegisterPersonsServer interface {
	SendAndClose(*PersonalInformationList) error
	Recv() (*PersonInformation, error)
	grpc.ServerStream
}

type rankServiceRegisterPersonsServer struct {
	grpc.ServerStream
}

func (x *rankServiceRegisterPersonsServer) SendAndClose(m *PersonalInformationList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rankServiceRegisterPersonsServer) Recv() (*PersonInformation, error) {
	m := new(PersonInformation)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RankService_WatchPersons_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Null)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RankServiceServer).WatchPersons(m, &rankServiceWatchPersonsServer{stream})
}

type RankService_WatchPersonsServer interface {
	Send(*PersonInformation) error
	grpc.ServerStream
}

type rankServiceWatchPersonsServer struct {
	grpc.ServerStream
}

func (x *rankServiceWatchPersonsServer) Send(m *PersonInformation) error {
	return x.ServerStream.SendMsg(m)
}

var _RankService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apis.RankService",
	HandlerType: (*RankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RankService_Register_Handler,
		},
		{
			MethodName: "UpdatePersonInformation",
			Handler:    _RankService_UpdatePersonInformation_Handler,
		},
		{
			MethodName: "GetFateRate",
			Handler:    _RankService_GetFateRate_Handler,
		},
		{
			MethodName: "GetTop",
			Handler:    _RankService_GetTop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterPersons",
			Handler:       _RankService_RegisterPersons_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchPersons",
			Handler:       _RankService_WatchPersons_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "types.proto",
>>>>>>> 0efc8eb... 0327
}
